name: Requiring test

on: pull_request

jobs:
  foo:
    name: Excluded test
    runs-on: ubuntu-latest
    if: false

    steps:
      - run: /bin/true

  bar:
    name: Excluded matrix test (${{ matrix.thing }})
    runs-on: ubuntu-latest
    if: false && matrix.thing == matrix.thing

    strategy:
      matrix:
        thing: [ "1", "2" ]

    steps:
      - run: /bin/true
